### ISSUE TITLE
models: weighted_hinge_loss()

### ISSUE THREAD

**Issue by luisfrancs** [juliacamps/FOG#1]
Hello, ¿Could you confirm if in line 39 is correct the  simbol \\ at the end
`hinge_neg = K.mean(K.maximum(1. - y_neg * y_pred, 0.)) * \`

**Comment by juliacamps** [comment]
> 
> 
> Hello, ¿Could you confirm if in line 39 is correct the simbol \ at the end
> `hinge_neg = K.mean(K.maximum(1. - y_neg * y_pred, 0.)) * \`

Links to the next line, it's correct. This may vary depending on your Python version though.
